# Generated by Django 5.2.6 on 2025-10-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='feedback',
            field=models.CharField(blank=True, choices=[('GOOD', 'Good'), ('BAD', 'Bad')], default=None, max_length=4, null=True),
        ),
    ]
